### ISSUE TITLE
command not found - csvcut command

### ISSUE THREAD

**Issue by petres** [balkey/eu1420#2]
In https://github.com/balkey/eu1420/blob/307b0353311645d92deaa195473a4ebae6dc15e8/cut_csv_columns.sh#L4 the command ```csvcut``` is called, which is not mentioned as requirement. 

Is this command from ```csvtools```? If, it should be mentioned as dependency.

**Comment by balkey** [comment]
Thanks for this, this is resolved in:
https://github.com/balkey/eu1420/commit/74c3b736f6cb124a050a37758f101962e9d57423
